# Generated by Django 4.2.3 on 2023-07-23 06:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todoapps", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"verbose_name": "TODOタスク"},
        ),
        migrations.AlterModelOptions(
            name="todocategory",
            options={"verbose_name": "TODOカテゴリ"},
        ),
    ]
